baseURL: "https://tuusuario.github.io/"
languageCode: en-us
title: "Global News Intelligence"
theme: "terminal"

# Permite archivos estáticos
staticDir = ["static"]

# Para incrustar HTML
markup:
  goldmark:
    renderer:
      unsafe: true
