baseURL: "https://jluisvim.github.io/event-context/"
languageCode: en-us
title: "Event Context | Global News Intelligence"
theme: "terminal"

# Permite archivos estáticos
staticDir:
  - static

# Para incrustar HTML
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  env: production
  title: Event Context
  description: "Daily AI-powered analysis of global news and event relationships."
  author: JLuisVM
  showReadingTime: true
  hideFooter: false
